Update README.md
FyraLabs/readymade pull request #20
Opened 2024-09-07 02:30 UTC by Owen-sz

Add systemd-repart and remove lyrics

2024-09-07 02:43 UTC, nothingneko requested changes

2024-09-07 02:43 UTC, nothingneko commented on README.md
> -
don't delete it all, just the lyrics

```
Readymade is named after Ado's single, [Readymade](https://youtu.be/jg09lNupc1s) which happens to have a cool double meaning to it as this installer essentially installs ready-made squashfs images.

The lyrics themselves could be seen as an insult to people overcomplicating things for themselves (e.g. Arch installation.)

2024-09-07 02:44 UTC, Owen-sz commented on README.md
> -
Ok, I'll add that second sentence back.

2024-09-11 21:48 UTC, nothingneko approved these changes

2024-09-11 21:48 UTC, merged